import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PropsWithChildren, Suspense } from "react";
import { GenreProvider } from "./_components/GenreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense>
          <GenreProvider>
            <div className="w-full lg:max-w-[1440px] lg:mx-auto">
              {children}
            </div>
          </GenreProvider>
        </Suspense>
      </body>
    </html>
  );
}
